spring:
  config:
    import: optional:file:.env[.properties]

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000

logging:
  level:
    root: info

server:
  port: 8090
  error:
    include-stacktrace: never
